/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FindJobsRouteImport } from './routes/find-jobs'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as Salary2RouteImport } from './routes/salary-2'
import { Route as SalaryCalculatorRouteImport } from './routes/salary-calculator'
import { Route as SalaryCheckRouteImport } from './routes/salary-check'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminCareersRouteImport } from './routes/admin.careers'
import { Route as ApiAiAssistantRouteImport } from './routes/api.ai-assistant'
import { Route as ApiBlogsRouteImport } from './routes/api.blogs'
import { Route as ApiCategoriesRouteImport } from './routes/api.categories'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as ApiFaqsRouteImport } from './routes/api.faqs'
import { Route as ApiResumeRouteImport } from './routes/api.resume'
import { Route as ApiSalaryAssistantRouteImport } from './routes/api.salary-assistant'
import { Route as ApiSalaryInsightsRouteImport } from './routes/api.salary-insights'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'
import { Route as CareersResumeBuilderRouteImport } from './routes/careers.resume-builder'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ApiCareersApplicationsRouteImport } from './routes/api.careers.applications'
import { Route as ApiCareersJobsRouteImport } from './routes/api.careers.jobs'
import { Route as ApiSalaryChatRouteImport } from './routes/api.salary.chat'
import { Route as ApiSalaryResearchRouteImport } from './routes/api.salary.research'
import { Route as CareersSlugApplyRouteImport } from './routes/careers.$slug.apply'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FindJobsRoute = FindJobsRouteImport.update({
  id: '/find-jobs',
  path: '/find-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const Salary2Route = Salary2RouteImport.update({
  id: '/salary-2',
  path: '/salary-2',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryCalculatorRoute = SalaryCalculatorRouteImport.update({
  id: '/salary-calculator',
  path: '/salary-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryCheckRoute = SalaryCheckRouteImport.update({
  id: '/salary-check',
  path: '/salary-check',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCareersRoute = AdminCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAiAssistantRoute = ApiAiAssistantRouteImport.update({
  id: '/api/ai-assistant',
  path: '/api/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogsRoute = ApiBlogsRouteImport.update({
  id: '/api/blogs',
  path: '/api/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFaqsRoute = ApiFaqsRouteImport.update({
  id: '/api/faqs',
  path: '/api/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResumeRoute = ApiResumeRouteImport.update({
  id: '/api/resume',
  path: '/api/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSalaryAssistantRoute = ApiSalaryAssistantRouteImport.update({
  id: '/api/salary-assistant',
  path: '/api/salary-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSalaryInsightsRoute = ApiSalaryInsightsRouteImport.update({
  id: '/api/salary-insights',
  path: '/api/salary-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersResumeBuilderRoute = CareersResumeBuilderRouteImport.update({
  id: '/careers/resume-builder',
  path: '/careers/resume-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCareersApplicationsRoute = ApiCareersApplicationsRouteImport.update({
  id: '/api/careers/applications',
  path: '/api/careers/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCareersJobsRoute = ApiCareersJobsRouteImport.update({
  id: '/api/careers/jobs',
  path: '/api/careers/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSalaryChatRoute = ApiSalaryChatRouteImport.update({
  id: '/api/salary/chat',
  path: '/api/salary/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSalaryResearchRoute = ApiSalaryResearchRouteImport.update({
  id: '/api/salary/research',
  path: '/api/salary/research',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSlugApplyRoute = CareersSlugApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => CareersSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-assistant': typeof AiAssistantRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/find-jobs': typeof FindJobsRoute
  '/gallery': typeof GalleryRoute
  '/jobs': typeof JobsRoute
  '/salary-2': typeof Salary2Route
  '/salary-calculator': typeof SalaryCalculatorRoute
  '/salary-check': typeof SalaryCheckRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/careers': typeof AdminCareersRoute
  '/api/ai-assistant': typeof ApiAiAssistantRoute
  '/api/blogs': typeof ApiBlogsRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/contact': typeof ApiContactRoute
  '/api/faqs': typeof ApiFaqsRoute
  '/api/resume': typeof ApiResumeRoute
  '/api/salary-assistant': typeof ApiSalaryAssistantRoute
  '/api/salary-insights': typeof ApiSalaryInsightsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/careers/$slug': typeof CareersSlugRouteWithChildren
  '/careers/resume-builder': typeof CareersResumeBuilderRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/careers/applications': typeof ApiCareersApplicationsRoute
  '/api/careers/jobs': typeof ApiCareersJobsRoute
  '/api/salary/chat': typeof ApiSalaryChatRoute
  '/api/salary/research': typeof ApiSalaryResearchRoute
  '/careers/$slug/apply': typeof CareersSlugApplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-assistant': typeof AiAssistantRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/find-jobs': typeof FindJobsRoute
  '/gallery': typeof GalleryRoute
  '/jobs': typeof JobsRoute
  '/salary-2': typeof Salary2Route
  '/salary-calculator': typeof SalaryCalculatorRoute
  '/salary-check': typeof SalaryCheckRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/careers': typeof AdminCareersRoute
  '/api/ai-assistant': typeof ApiAiAssistantRoute
  '/api/blogs': typeof ApiBlogsRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/contact': typeof ApiContactRoute
  '/api/faqs': typeof ApiFaqsRoute
  '/api/resume': typeof ApiResumeRoute
  '/api/salary-assistant': typeof ApiSalaryAssistantRoute
  '/api/salary-insights': typeof ApiSalaryInsightsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/careers/$slug': typeof CareersSlugRouteWithChildren
  '/careers/resume-builder': typeof CareersResumeBuilderRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/careers': typeof CareersIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/api/careers/applications': typeof ApiCareersApplicationsRoute
  '/api/careers/jobs': typeof ApiCareersJobsRoute
  '/api/salary/chat': typeof ApiSalaryChatRoute
  '/api/salary/research': typeof ApiSalaryResearchRoute
  '/careers/$slug/apply': typeof CareersSlugApplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-assistant': typeof AiAssistantRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/find-jobs': typeof FindJobsRoute
  '/gallery': typeof GalleryRoute
  '/jobs': typeof JobsRoute
  '/salary-2': typeof Salary2Route
  '/salary-calculator': typeof SalaryCalculatorRoute
  '/salary-check': typeof SalaryCheckRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/careers': typeof AdminCareersRoute
  '/api/ai-assistant': typeof ApiAiAssistantRoute
  '/api/blogs': typeof ApiBlogsRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/contact': typeof ApiContactRoute
  '/api/faqs': typeof ApiFaqsRoute
  '/api/resume': typeof ApiResumeRoute
  '/api/salary-assistant': typeof ApiSalaryAssistantRoute
  '/api/salary-insights': typeof ApiSalaryInsightsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/careers/$slug': typeof CareersSlugRouteWithChildren
  '/careers/resume-builder': typeof CareersResumeBuilderRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/careers/applications': typeof ApiCareersApplicationsRoute
  '/api/careers/jobs': typeof ApiCareersJobsRoute
  '/api/salary/chat': typeof ApiSalaryChatRoute
  '/api/salary/research': typeof ApiSalaryResearchRoute
  '/careers/$slug/apply': typeof CareersSlugApplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-assistant'
    | '/contact'
    | '/faq'
    | '/find-jobs'
    | '/gallery'
    | '/jobs'
    | '/salary-2'
    | '/salary-calculator'
    | '/salary-check'
    | '/sitemap'
    | '/sitemap.xml'
    | '/admin/careers'
    | '/api/ai-assistant'
    | '/api/blogs'
    | '/api/categories'
    | '/api/contact'
    | '/api/faqs'
    | '/api/resume'
    | '/api/salary-assistant'
    | '/api/salary-insights'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/careers/resume-builder'
    | '/industries/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/careers/'
    | '/industries/'
    | '/services/'
    | '/api/careers/applications'
    | '/api/careers/jobs'
    | '/api/salary/chat'
    | '/api/salary/research'
    | '/careers/$slug/apply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-assistant'
    | '/contact'
    | '/faq'
    | '/find-jobs'
    | '/gallery'
    | '/jobs'
    | '/salary-2'
    | '/salary-calculator'
    | '/salary-check'
    | '/sitemap'
    | '/sitemap.xml'
    | '/admin/careers'
    | '/api/ai-assistant'
    | '/api/blogs'
    | '/api/categories'
    | '/api/contact'
    | '/api/faqs'
    | '/api/resume'
    | '/api/salary-assistant'
    | '/api/salary-insights'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/careers/resume-builder'
    | '/industries/$slug'
    | '/services/$slug'
    | '/blog'
    | '/careers'
    | '/industries'
    | '/services'
    | '/api/careers/applications'
    | '/api/careers/jobs'
    | '/api/salary/chat'
    | '/api/salary/research'
    | '/careers/$slug/apply'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-assistant'
    | '/contact'
    | '/faq'
    | '/find-jobs'
    | '/gallery'
    | '/jobs'
    | '/salary-2'
    | '/salary-calculator'
    | '/salary-check'
    | '/sitemap'
    | '/sitemap.xml'
    | '/admin/careers'
    | '/api/ai-assistant'
    | '/api/blogs'
    | '/api/categories'
    | '/api/contact'
    | '/api/faqs'
    | '/api/resume'
    | '/api/salary-assistant'
    | '/api/salary-insights'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/careers/resume-builder'
    | '/industries/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/careers/'
    | '/industries/'
    | '/services/'
    | '/api/careers/applications'
    | '/api/careers/jobs'
    | '/api/salary/chat'
    | '/api/salary/research'
    | '/careers/$slug/apply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiAssistantRoute: typeof AiAssistantRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FindJobsRoute: typeof FindJobsRoute
  GalleryRoute: typeof GalleryRoute
  JobsRoute: typeof JobsRoute
  Salary2Route: typeof Salary2Route
  SalaryCalculatorRoute: typeof SalaryCalculatorRoute
  SalaryCheckRoute: typeof SalaryCheckRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAiAssistantRoute: typeof ApiAiAssistantRoute
  ApiBlogsRoute: typeof ApiBlogsRoute
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiFaqsRoute: typeof ApiFaqsRoute
  ApiResumeRoute: typeof ApiResumeRoute
  ApiSalaryAssistantRoute: typeof ApiSalaryAssistantRoute
  ApiSalaryInsightsRoute: typeof ApiSalaryInsightsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CareersSlugRoute: typeof CareersSlugRouteWithChildren
  CareersResumeBuilderRoute: typeof CareersResumeBuilderRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CareersIndexRoute: typeof CareersIndexRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiCareersApplicationsRoute: typeof ApiCareersApplicationsRoute
  ApiCareersJobsRoute: typeof ApiCareersJobsRoute
  ApiSalaryChatRoute: typeof ApiSalaryChatRoute
  ApiSalaryResearchRoute: typeof ApiSalaryResearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-jobs': {
      id: '/find-jobs'
      path: '/find-jobs'
      fullPath: '/find-jobs'
      preLoaderRoute: typeof FindJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-2': {
      id: '/salary-2'
      path: '/salary-2'
      fullPath: '/salary-2'
      preLoaderRoute: typeof Salary2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-calculator': {
      id: '/salary-calculator'
      path: '/salary-calculator'
      fullPath: '/salary-calculator'
      preLoaderRoute: typeof SalaryCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-check': {
      id: '/salary-check'
      path: '/salary-check'
      fullPath: '/salary-check'
      preLoaderRoute: typeof SalaryCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/careers': {
      id: '/admin/careers'
      path: '/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminCareersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/ai-assistant': {
      id: '/api/ai-assistant'
      path: '/api/ai-assistant'
      fullPath: '/api/ai-assistant'
      preLoaderRoute: typeof ApiAiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blogs': {
      id: '/api/blogs'
      path: '/api/blogs'
      fullPath: '/api/blogs'
      preLoaderRoute: typeof ApiBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/faqs': {
      id: '/api/faqs'
      path: '/api/faqs'
      fullPath: '/api/faqs'
      preLoaderRoute: typeof ApiFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resume': {
      id: '/api/resume'
      path: '/api/resume'
      fullPath: '/api/resume'
      preLoaderRoute: typeof ApiResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/salary-assistant': {
      id: '/api/salary-assistant'
      path: '/api/salary-assistant'
      fullPath: '/api/salary-assistant'
      preLoaderRoute: typeof ApiSalaryAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/salary-insights': {
      id: '/api/salary-insights'
      path: '/api/salary-insights'
      fullPath: '/api/salary-insights'
      preLoaderRoute: typeof ApiSalaryInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/resume-builder': {
      id: '/careers/resume-builder'
      path: '/careers/resume-builder'
      fullPath: '/careers/resume-builder'
      preLoaderRoute: typeof CareersResumeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/careers/applications': {
      id: '/api/careers/applications'
      path: '/api/careers/applications'
      fullPath: '/api/careers/applications'
      preLoaderRoute: typeof ApiCareersApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/careers/jobs': {
      id: '/api/careers/jobs'
      path: '/api/careers/jobs'
      fullPath: '/api/careers/jobs'
      preLoaderRoute: typeof ApiCareersJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/salary/chat': {
      id: '/api/salary/chat'
      path: '/api/salary/chat'
      fullPath: '/api/salary/chat'
      preLoaderRoute: typeof ApiSalaryChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/salary/research': {
      id: '/api/salary/research'
      path: '/api/salary/research'
      fullPath: '/api/salary/research'
      preLoaderRoute: typeof ApiSalaryResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$slug/apply': {
      id: '/careers/$slug/apply'
      path: '/apply'
      fullPath: '/careers/$slug/apply'
      preLoaderRoute: typeof CareersSlugApplyRouteImport
      parentRoute: typeof CareersSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCareersRoute: typeof AdminCareersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCareersRoute: AdminCareersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CareersSlugRouteChildren {
  CareersSlugApplyRoute: typeof CareersSlugApplyRoute
}

const CareersSlugRouteChildren: CareersSlugRouteChildren = {
  CareersSlugApplyRoute: CareersSlugApplyRoute,
}

const CareersSlugRouteWithChildren = CareersSlugRoute._addFileChildren(
  CareersSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiAssistantRoute: AiAssistantRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FindJobsRoute: FindJobsRoute,
  GalleryRoute: GalleryRoute,
  JobsRoute: JobsRoute,
  Salary2Route: Salary2Route,
  SalaryCalculatorRoute: SalaryCalculatorRoute,
  SalaryCheckRoute: SalaryCheckRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAiAssistantRoute: ApiAiAssistantRoute,
  ApiBlogsRoute: ApiBlogsRoute,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiContactRoute: ApiContactRoute,
  ApiFaqsRoute: ApiFaqsRoute,
  ApiResumeRoute: ApiResumeRoute,
  ApiSalaryAssistantRoute: ApiSalaryAssistantRoute,
  ApiSalaryInsightsRoute: ApiSalaryInsightsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CareersSlugRoute: CareersSlugRouteWithChildren,
  CareersResumeBuilderRoute: CareersResumeBuilderRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CareersIndexRoute: CareersIndexRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiCareersApplicationsRoute: ApiCareersApplicationsRoute,
  ApiCareersJobsRoute: ApiCareersJobsRoute,
  ApiSalaryChatRoute: ApiSalaryChatRoute,
  ApiSalaryResearchRoute: ApiSalaryResearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
