/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminCareersRouteImport } from './routes/admin_.careers'
import { Route as ApiBlogsRouteImport } from './routes/api.blogs'
import { Route as ApiCategoriesRouteImport } from './routes/api.categories'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as ApiFaqsRouteImport } from './routes/api.faqs'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'
import { Route as CareersResumeBuilderRouteImport } from './routes/careers.resume-builder'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ApiCareersApplicationsRouteImport } from './routes/api.careers.applications'
import { Route as ApiCareersJobsRouteImport } from './routes/api.careers.jobs'
import { Route as CareersSlugApplyRouteImport } from './routes/careers.$slug.apply'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCareersRoute = AdminCareersRouteImport.update({
  id: '/admin_/careers',
  path: '/admin/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogsRoute = ApiBlogsRouteImport.update({
  id: '/api/blogs',
  path: '/api/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFaqsRoute = ApiFaqsRouteImport.update({
  id: '/api/faqs',
  path: '/api/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersResumeBuilderRoute = CareersResumeBuilderRouteImport.update({
  id: '/careers/resume-builder',
  path: '/careers/resume-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCareersApplicationsRoute = ApiCareersApplicationsRouteImport.update({
  id: '/api/careers/applications',
  path: '/api/careers/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCareersJobsRoute = ApiCareersJobsRouteImport.update({
  id: '/api/careers/jobs',
  path: '/api/careers/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSlugApplyRoute = CareersSlugApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => CareersSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/careers': typeof AdminCareersRoute
  '/api/blogs': typeof ApiBlogsRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/contact': typeof ApiContactRoute
  '/api/faqs': typeof ApiFaqsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/careers/$slug': typeof CareersSlugRouteWithChildren
  '/careers/resume-builder': typeof CareersResumeBuilderRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/careers/applications': typeof ApiCareersApplicationsRoute
  '/api/careers/jobs': typeof ApiCareersJobsRoute
  '/careers/$slug/apply': typeof CareersSlugApplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/careers': typeof AdminCareersRoute
  '/api/blogs': typeof ApiBlogsRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/contact': typeof ApiContactRoute
  '/api/faqs': typeof ApiFaqsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/careers/$slug': typeof CareersSlugRouteWithChildren
  '/careers/resume-builder': typeof CareersResumeBuilderRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/careers': typeof CareersIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/api/careers/applications': typeof ApiCareersApplicationsRoute
  '/api/careers/jobs': typeof ApiCareersJobsRoute
  '/careers/$slug/apply': typeof CareersSlugApplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin_/careers': typeof AdminCareersRoute
  '/api/blogs': typeof ApiBlogsRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/contact': typeof ApiContactRoute
  '/api/faqs': typeof ApiFaqsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/careers/$slug': typeof CareersSlugRouteWithChildren
  '/careers/resume-builder': typeof CareersResumeBuilderRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/careers/applications': typeof ApiCareersApplicationsRoute
  '/api/careers/jobs': typeof ApiCareersJobsRoute
  '/careers/$slug/apply': typeof CareersSlugApplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/sitemap.xml'
    | '/admin/careers'
    | '/api/blogs'
    | '/api/categories'
    | '/api/contact'
    | '/api/faqs'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/careers/resume-builder'
    | '/industries/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/careers/'
    | '/industries/'
    | '/services/'
    | '/api/careers/applications'
    | '/api/careers/jobs'
    | '/careers/$slug/apply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/sitemap.xml'
    | '/admin/careers'
    | '/api/blogs'
    | '/api/categories'
    | '/api/contact'
    | '/api/faqs'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/careers/resume-builder'
    | '/industries/$slug'
    | '/services/$slug'
    | '/blog'
    | '/careers'
    | '/industries'
    | '/services'
    | '/api/careers/applications'
    | '/api/careers/jobs'
    | '/careers/$slug/apply'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/sitemap.xml'
    | '/admin_/careers'
    | '/api/blogs'
    | '/api/categories'
    | '/api/contact'
    | '/api/faqs'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/careers/resume-builder'
    | '/industries/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/careers/'
    | '/industries/'
    | '/services/'
    | '/api/careers/applications'
    | '/api/careers/jobs'
    | '/careers/$slug/apply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminCareersRoute: typeof AdminCareersRoute
  ApiBlogsRoute: typeof ApiBlogsRoute
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiFaqsRoute: typeof ApiFaqsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CareersSlugRoute: typeof CareersSlugRouteWithChildren
  CareersResumeBuilderRoute: typeof CareersResumeBuilderRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CareersIndexRoute: typeof CareersIndexRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiCareersApplicationsRoute: typeof ApiCareersApplicationsRoute
  ApiCareersJobsRoute: typeof ApiCareersJobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/careers': {
      id: '/admin_/careers'
      path: '/admin/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blogs': {
      id: '/api/blogs'
      path: '/api/blogs'
      fullPath: '/api/blogs'
      preLoaderRoute: typeof ApiBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/faqs': {
      id: '/api/faqs'
      path: '/api/faqs'
      fullPath: '/api/faqs'
      preLoaderRoute: typeof ApiFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/resume-builder': {
      id: '/careers/resume-builder'
      path: '/careers/resume-builder'
      fullPath: '/careers/resume-builder'
      preLoaderRoute: typeof CareersResumeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/careers/applications': {
      id: '/api/careers/applications'
      path: '/api/careers/applications'
      fullPath: '/api/careers/applications'
      preLoaderRoute: typeof ApiCareersApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/careers/jobs': {
      id: '/api/careers/jobs'
      path: '/api/careers/jobs'
      fullPath: '/api/careers/jobs'
      preLoaderRoute: typeof ApiCareersJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$slug/apply': {
      id: '/careers/$slug/apply'
      path: '/apply'
      fullPath: '/careers/$slug/apply'
      preLoaderRoute: typeof CareersSlugApplyRouteImport
      parentRoute: typeof CareersSlugRoute
    }
  }
}

interface CareersSlugRouteChildren {
  CareersSlugApplyRoute: typeof CareersSlugApplyRoute
}

const CareersSlugRouteChildren: CareersSlugRouteChildren = {
  CareersSlugApplyRoute: CareersSlugApplyRoute,
}

const CareersSlugRouteWithChildren = CareersSlugRoute._addFileChildren(
  CareersSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminCareersRoute: AdminCareersRoute,
  ApiBlogsRoute: ApiBlogsRoute,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiContactRoute: ApiContactRoute,
  ApiFaqsRoute: ApiFaqsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CareersSlugRoute: CareersSlugRouteWithChildren,
  CareersResumeBuilderRoute: CareersResumeBuilderRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CareersIndexRoute: CareersIndexRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiCareersApplicationsRoute: ApiCareersApplicationsRoute,
  ApiCareersJobsRoute: ApiCareersJobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
